import {
  Injectable,
  NotFoundException,
  BadRequestException,
  Logger,
} from '@nestjs/common';
import * as mysql from 'mysql2/promise';
import type { Response } from 'express';
import {
  createMysqlPool,
  buildSshConfig,
  type SshConfig,
} from '../common/db/mysql-pool';
import { PrismaService } from '../../prisma/prisma.service';
import { EncryptionService } from '../common/encryption/encryption.service';
import { MigrationValidationService } from './validation/migration-validation.service';

type Conflict = 'skip' | 'truncate' | 'upsert';

interface ConnInfo {
  host: string;
  port: number;
  databaseName: string;
  username: string;
  encryptedPassword: string;
  sslEnabled: boolean;
  name: string;
  ssh?: SshConfig;
}

interface BaseTable {
  name: string;
  rows: number;
}

const BATCH = 2000;
const SCRIPT_ROW_CAP = 100_000;
const IDENT = /^[A-Za-z0-9_$]+$/;

@Injectable()
export class DataMigrationService {
  private readonly logger = new Logger(DataMigrationService.name);

  constructor(
    private prisma: PrismaService,
    private encryption: EncryptionService,
    private validation: MigrationValidationService,
  ) {}

  // ─── Plan (dry-run preview) ──────────────────────────────

  async plan(workspaceId: string, sourceId: string, targetId: string) {
    if (sourceId === targetId) {
      throw new BadRequestException('Source and target must be different.');
    }
    const source = await this.load(sourceId, workspaceId);
    const target = await this.load(targetId, workspaceId);
    const { pool: sPool, cleanup: sCleanup } = await this.pool(source);
    const { pool: tPool, cleanup: tCleanup } = await this.pool(target);

    try {
      const sTables = await this.baseTables(sPool, source.databaseName);
      const tBase = await this.baseTables(tPool, target.databaseName);
      const tExisting = new Map(tBase.map((t) => [t.name, t.rows]));
      const fks = await this.foreignKeys(sPool, source.databaseName);
      const order = this.topoOrder(
        sTables.map((t) => t.name),
        fks,
      );
      const rank = new Map(order.map((n, i) => [n, i]));

      const tables = sTables
        .map((t) => ({
          tableName: t.name,
          sourceRows: t.rows,
          existsOnTarget: tExisting.has(t.name),
          targetRows: tExisting.get(t.name) ?? null,
        }))
        .sort((a, b) => (rank.get(a.tableName)! - rank.get(b.tableName)!));

      return {
        source: { id: sourceId, name: source.name, database: source.databaseName },
        target: { id: targetId, name: target.name, database: target.databaseName },
        order,
        tables,
      };
    } finally {
      await sCleanup();
      await tCleanup();
    }
  }

  // ─── Script generation ───────────────────────────────────

  async generateScript(
    workspaceId: string,
    dto: {
      sourceConnectionId: string;
      targetConnectionId: string;
      tables: string[];
      createTables: boolean;
      conflict: Conflict;
    },
  ): Promise<{ sql: string; truncated: boolean; rowsIncluded: number }> {
    const source = await this.load(dto.sourceConnectionId, workspaceId);
    const { pool: sPool, cleanup: sCleanup } = await this.pool(source);
    const conn = await sPool.getConnection();
    try {
      const ordered = await this.orderTables(sPool, source.databaseName, dto.tables);
      const parts: string[] = [
        '-- Migration script generated by QuerySense',
        `-- Source: ${source.name} (${source.databaseName})`,
        'SET FOREIGN_KEY_CHECKS=0;',
        '',
      ];
      let rowsIncluded = 0;
      let truncated = false;

      for (const table of ordered) {
        this.assertIdent(table);
        if (dto.createTables) {
          const [rows] = await conn.query<mysql.RowDataPacket[]>(
            `SHOW CREATE TABLE \`${table}\``,
          );
          const ddl = String(
            (rows[0] as Record<string, unknown>)['Create Table'] ?? '',
          );
          parts.push(`DROP TABLE IF EXISTS \`${table}\`;`, `${ddl};`, '');
        }

        const cols = await this.insertableColumns(sPool, source.databaseName, table);
        if (cols.length === 0) continue;
        if (dto.conflict === 'truncate') parts.push(`TRUNCATE TABLE \`${table}\`;`);

        const insertSql = this.insertTemplate(dto.conflict, table, cols);
        let offset = 0;
        let tableRows = 0;
        for (;;) {
          if (tableRows >= SCRIPT_ROW_CAP) {
            truncated = true;
            parts.push(
              `-- NOTE: \`${table}\` truncated at ${SCRIPT_ROW_CAP} rows in this script. Use direct copy for the full table.`,
            );
            break;
          }
          const [data] = await conn.query<mysql.RowDataPacket[]>(
            `SELECT ${cols.map((c) => `\`${c}\``).join(', ')} FROM \`${table}\` LIMIT ? OFFSET ?`,
            [BATCH, offset],
          );
          if (data.length === 0) break;
          const values = data.map((r) =>
            cols.map((c) => this.normalizeValue((r as Record<string, unknown>)[c])),
          );
          parts.push(conn.format(insertSql, [values]) + ';');
          tableRows += data.length;
          rowsIncluded += data.length;
          offset += data.length;
          if (data.length < BATCH) break;
        }
        parts.push('');
      }

      parts.push('SET FOREIGN_KEY_CHECKS=1;');
      return { sql: parts.join('\n'), truncated, rowsIncluded };
    } finally {
      conn.release();
      await sCleanup();
    }
  }

  // ─── Direct copy (SSE) ───────────────────────────────────

  async run(
    workspaceId: string,
    dto: {
      sourceConnectionId: string;
      targetConnectionId: string;
      tables: string[];
      createTables: boolean;
      conflict: Conflict;
      skipValidation?: boolean;
    },
    res: Response,
  ): Promise<void> {
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.flushHeaders();
    const send = (event: string, data: unknown) =>
      res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);

    // Pre-flight validation gate: never start if a BLOCKER is present.
    if (!dto.skipValidation) {
      try {
        const blockers = await this.validation.hasBlockingIssues(workspaceId, {
          sourceConnectionId: dto.sourceConnectionId,
          targetConnectionId: dto.targetConnectionId,
          tables: dto.tables,
          mode: dto.conflict === 'truncate' ? 'overwrite' : 'append',
        });
        if (blockers.length > 0) {
          send('error', {
            message: `Migration blocked by ${blockers.length} validation blocker(s).`,
            blockers,
          });
          res.end();
          return;
        }
      } catch (err) {
        this.logger.warn(
          `Pre-flight validation could not complete: ${err instanceof Error ? err.message : 'unknown'}`,
        );
      }
    }

    let sPool: mysql.Pool | null = null;
    let target: ConnInfo | null = null;
    let tConn: mysql.PoolConnection | null = null;
    let tPool: mysql.Pool | null = null;
    let sCleanup: (() => Promise<void>) | null = null;
    let tCleanup: (() => Promise<void>) | null = null;

    const report: Array<{
      table: string;
      copied: number;
      sourceRows: number;
      targetRows: number;
      status: string;
      error?: string;
    }> = [];

    try {
      if (dto.sourceConnectionId === dto.targetConnectionId) {
        throw new BadRequestException('Source and target must be different.');
      }
      const source = await this.load(dto.sourceConnectionId, workspaceId);
      target = await this.load(dto.targetConnectionId, workspaceId);
      ({ pool: sPool, cleanup: sCleanup } = await this.pool(source));
      ({ pool: tPool, cleanup: tCleanup } = await this.pool(target));
      tConn = await tPool.getConnection();
      await tConn.query('SET SESSION FOREIGN_KEY_CHECKS=0');
      await tConn.query('SET SESSION UNIQUE_CHECKS=0');

      const ordered = await this.orderTables(sPool, source.databaseName, dto.tables);
      const targetExisting = new Set(
        (await this.baseTables(tPool, target.databaseName)).map((t) => t.name),
      );

      for (const table of ordered) {
        this.assertIdent(table);
        send('table', { table, status: 'start' });
        try {
          if (dto.createTables && !targetExisting.has(table)) {
            const sConn = await sPool.getConnection();
            try {
              const [rows] = await sConn.query<mysql.RowDataPacket[]>(
                `SHOW CREATE TABLE \`${table}\``,
              );
              const ddl = String(
                (rows[0] as Record<string, unknown>)['Create Table'] ?? '',
              );
              await tConn.query(ddl);
            } finally {
              sConn.release();
            }
            send('table', { table, status: 'created' });
          }

          if (dto.conflict === 'truncate') {
            await tConn.query(`TRUNCATE TABLE \`${table}\``);
          }

          const copied = await this.copyTable(
            sPool,
            tConn,
            source.databaseName,
            table,
            dto.conflict,
            (n, total) => send('progress', { table, copied: n, total }),
          );

          const sourceRows = await this.count(sPool, table);
          const targetRows = await this.count(tPool, table);
          report.push({ table, copied, sourceRows, targetRows, status: 'done' });
          send('table', { table, status: 'done', copied, sourceRows, targetRows });
        } catch (err) {
          const msg = err instanceof Error ? err.message : 'copy failed';
          report.push({ table, copied: 0, sourceRows: 0, targetRows: 0, status: 'error', error: msg });
          send('table', { table, status: 'error', error: msg });
        }
      }

      await tConn.query('SET SESSION FOREIGN_KEY_CHECKS=1');
      send('done', { report });
      res.end();
    } catch (err) {
      send('error', {
        message: err instanceof Error ? err.message : 'Migration failed',
      });
      res.end();
    } finally {
      if (tConn) {
        try {
          await tConn.query('SET SESSION FOREIGN_KEY_CHECKS=1');
        } catch {
          /* ignore */
        }
        tConn.release();
      }
      if (sCleanup) await sCleanup();
      if (tCleanup) await tCleanup();
    }
  }

  private async copyTable(
    sPool: mysql.Pool,
    tConn: mysql.PoolConnection,
    db: string,
    table: string,
    conflict: Conflict,
    onProgress: (copied: number, total: number) => void,
  ): Promise<number> {
    const cols = await this.insertableColumns(sPool, db, table);
    if (cols.length === 0) return 0;
    const pk = await this.primaryKey(sPool, db, table);
    const total = await this.count(sPool, table);
    const colList = cols.map((c) => `\`${c}\``).join(', ');
    const insertSql = this.insertTemplate(conflict, table, cols);

    let copied = 0;

    // Keyset pagination when there's a single-column PK; OFFSET otherwise.
    if (pk.length === 1) {
      const key = pk[0];
      let last: unknown = null;
      for (;;) {
        const where = last === null ? '' : `WHERE \`${key}\` > ?`;
        const params = last === null ? [BATCH] : [last, BATCH];
        const [rows] = await sPool.query<mysql.RowDataPacket[]>(
          `SELECT ${colList} FROM \`${table}\` ${where} ORDER BY \`${key}\` ASC LIMIT ?`,
          params,
        );
        if (rows.length === 0) break;
        await this.insertBatch(tConn, insertSql, cols, rows);
        copied += rows.length;
        last = (rows[rows.length - 1] as Record<string, unknown>)[key];
        onProgress(copied, total);
        if (rows.length < BATCH) break;
      }
    } else {
      let offset = 0;
      for (;;) {
        const [rows] = await sPool.query<mysql.RowDataPacket[]>(
          `SELECT ${colList} FROM \`${table}\` LIMIT ? OFFSET ?`,
          [BATCH, offset],
        );
        if (rows.length === 0) break;
        await this.insertBatch(tConn, insertSql, cols, rows);
        copied += rows.length;
        offset += rows.length;
        onProgress(copied, total);
        if (rows.length < BATCH) break;
      }
    }
    return copied;
  }

  private async insertBatch(
    tConn: mysql.PoolConnection,
    sql: string,
    cols: string[],
    rows: mysql.RowDataPacket[],
  ) {
    const values = rows.map((r) =>
      cols.map((c) => this.normalizeValue((r as Record<string, unknown>)[c])),
    );
    await tConn.query(sql, [values]);
  }

  /**
   * mysql2 returns JSON columns as parsed JS objects/arrays. A nested array
   * would be expanded by the bulk-insert formatter into a SQL row `(a,b)`,
   * breaking column counts — so serialize objects/arrays back to JSON text.
   * Dates and Buffers are left for mysql2 to handle.
   */
  private normalizeValue(v: unknown): unknown {
    if (
      v !== null &&
      typeof v === 'object' &&
      !(v instanceof Date) &&
      !Buffer.isBuffer(v)
    ) {
      return JSON.stringify(v);
    }
    return v;
  }

  /** Full parameterized INSERT (one `?` for the bulk VALUES) per conflict mode. */
  private insertTemplate(conflict: Conflict, table: string, cols: string[]): string {
    const colList = cols.map((c) => `\`${c}\``).join(', ');
    if (conflict === 'skip') {
      return `INSERT IGNORE INTO \`${table}\` (${colList}) VALUES ?`;
    }
    if (conflict === 'upsert') {
      const upd = cols.map((c) => `\`${c}\`=VALUES(\`${c}\`)`).join(', ');
      return `INSERT INTO \`${table}\` (${colList}) VALUES ? ON DUPLICATE KEY UPDATE ${upd}`;
    }
    return `INSERT INTO \`${table}\` (${colList}) VALUES ?`;
  }

  // ─── Introspection helpers ───────────────────────────────

  private async baseTables(pool: mysql.Pool, db: string): Promise<BaseTable[]> {
    const [rows] = await pool.query<mysql.RowDataPacket[]>(
      `SELECT TABLE_NAME, COALESCE(TABLE_ROWS,0) AS R
       FROM information_schema.TABLES
       WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = 'BASE TABLE' ORDER BY TABLE_NAME`,
      [db],
    );
    return rows.map((r) => ({
      name: String((r as Record<string, unknown>)['TABLE_NAME']),
      rows: Number((r as Record<string, unknown>)['R'] ?? 0),
    }));
  }

  private async foreignKeys(
    pool: mysql.Pool,
    db: string,
  ): Promise<Array<{ table: string; refTable: string }>> {
    const [rows] = await pool.query<mysql.RowDataPacket[]>(
      `SELECT TABLE_NAME, REFERENCED_TABLE_NAME
       FROM information_schema.KEY_COLUMN_USAGE
       WHERE TABLE_SCHEMA = ? AND REFERENCED_TABLE_NAME IS NOT NULL`,
      [db],
    );
    return rows.map((r) => ({
      table: String((r as Record<string, unknown>)['TABLE_NAME']),
      refTable: String((r as Record<string, unknown>)['REFERENCED_TABLE_NAME']),
    }));
  }

  private async primaryKey(
    pool: mysql.Pool,
    db: string,
    table: string,
  ): Promise<string[]> {
    const [rows] = await pool.query<mysql.RowDataPacket[]>(
      `SELECT COLUMN_NAME FROM information_schema.COLUMNS
       WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_KEY = 'PRI'
       ORDER BY ORDINAL_POSITION`,
      [db, table],
    );
    return rows.map((r) => String((r as Record<string, unknown>)['COLUMN_NAME']));
  }

  private async insertableColumns(
    pool: mysql.Pool,
    db: string,
    table: string,
  ): Promise<string[]> {
    const [rows] = await pool.query<mysql.RowDataPacket[]>(
      `SELECT COLUMN_NAME, EXTRA FROM information_schema.COLUMNS
       WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? ORDER BY ORDINAL_POSITION`,
      [db, table],
    );
    return rows
      .filter(
        (r) =>
          !String((r as Record<string, unknown>)['EXTRA'] ?? '')
            .toUpperCase()
            .includes('GENERATED'),
      )
      .map((r) => String((r as Record<string, unknown>)['COLUMN_NAME']));
  }

  private async count(pool: mysql.Pool, table: string): Promise<number> {
    const [rows] = await pool.query<mysql.RowDataPacket[]>(
      `SELECT COUNT(*) AS C FROM \`${table}\``,
    );
    return Number((rows[0] as Record<string, unknown>)['C'] ?? 0);
  }

  private async orderTables(
    pool: mysql.Pool,
    db: string,
    selected: string[],
  ): Promise<string[]> {
    const set = new Set(selected);
    const fks = (await this.foreignKeys(pool, db)).filter(
      (f) => set.has(f.table) && set.has(f.refTable),
    );
    return this.topoOrder(selected, fks);
  }

  /** Parents (referenced) before children. Cycles are appended in input order. */
  private topoOrder(
    tables: string[],
    fks: Array<{ table: string; refTable: string }>,
  ): string[] {
    const deps = new Map<string, Set<string>>();
    tables.forEach((t) => deps.set(t, new Set()));
    for (const f of fks) {
      if (f.table !== f.refTable && deps.has(f.table) && deps.has(f.refTable)) {
        deps.get(f.table)!.add(f.refTable);
      }
    }
    const out: string[] = [];
    const done = new Set<string>();
    while (out.length < tables.length) {
      const ready = tables.filter(
        (t) => !done.has(t) && [...deps.get(t)!].every((d) => done.has(d)),
      );
      if (ready.length === 0) {
        // cycle — append the rest in original order
        for (const t of tables) if (!done.has(t)) { out.push(t); done.add(t); }
        break;
      }
      for (const t of ready) {
        out.push(t);
        done.add(t);
      }
    }
    return out;
  }

  private assertIdent(name: string) {
    if (!IDENT.test(name)) {
      throw new BadRequestException(`Invalid table name "${name}".`);
    }
  }

  private async load(connectionId: string, workspaceId: string): Promise<ConnInfo> {
    const c = await this.prisma.databaseConnection.findFirst({
      where: { id: connectionId, workspaceId },
    });
    if (!c) throw new NotFoundException('Connection not found');
    return {
      host: c.host,
      port: c.port,
      databaseName: c.databaseName,
      username: c.username,
      encryptedPassword: c.encryptedPassword,
      sslEnabled: c.sslEnabled,
      name: c.name,
      ssh: buildSshConfig(c, (s) => this.encryption.decrypt(s)),
    };
  }

  private pool(c: ConnInfo) {
    return createMysqlPool({
      host: c.host,
      port: c.port,
      database: c.databaseName,
      user: c.username,
      password: this.encryption.decrypt(c.encryptedPassword),
      ssl: c.sslEnabled,
      ssh: c.ssh,
      connectionLimit: 4,
      connectTimeout: 10000,
    });
  }
}
