import { createPool, type SqlClient, type SqlExecutor } from '../../common/db/mysql-pool';
import { quoteIdent } from '../../common/db/engine';
import {
  BATCH,
  type BaseTable,
  type Conflict,
  type MigrationConn,
  type MigrationDriver,
} from './migration-driver';

const id = (n: string) => quoteIdent('oracle', n);

interface ColDdl {
  name: string;
  dataType: string;
  charLen: number | null;
  dataLen: number | null;
  prec: number | null;
  scale: number | null;
  nullable: boolean;
  identity: boolean;
  virtual: boolean;
  default: string | null;
}

function typeString(c: ColDdl): string {
  const t = c.dataType.toUpperCase();
  if (['VARCHAR2', 'NVARCHAR2', 'CHAR', 'NCHAR', 'RAW'].includes(t)) {
    const len = c.charLen && c.charLen > 0 ? c.charLen : c.dataLen ?? 255;
    return `${t}(${len})`;
  }
  if (t === 'NUMBER' && c.prec != null) {
    return `NUMBER(${c.prec},${c.scale ?? 0})`;
  }
  return t; // NUMBER, DATE, TIMESTAMP, CLOB, BLOB, BINARY_DOUBLE, FLOAT, ...
}

/**
 * Oracle (node-oracledb thin) data-migration strategy. Same-engine only. DDL is
 * reconstructed from USER_* views; identity columns are cloned as GENERATED BY
 * DEFAULT (so source values can be inserted) and reseeded afterwards. Skip/upsert
 * are done by pre-filtering / delete-then-insert (no MERGE). Scoped to the
 * connected user's schema; FK constraints and virtual columns aren't cloned.
 */
export class OracleMigrationDriver implements MigrationDriver {
  readonly engine = 'oracle' as const;

  private sClient!: SqlClient;
  private tClient!: SqlClient;

  constructor(
    private source: MigrationConn,
    private target: MigrationConn,
  ) {}

  private cfg(c: MigrationConn) {
    return {
      host: c.host,
      port: c.port,
      database: c.database,
      user: c.user,
      password: c.password,
      ssl: c.sslEnabled,
      ssh: c.ssh,
      connectionLimit: 4,
      connectTimeout: 10000,
    };
  }

  async openSource(): Promise<void> {
    this.sClient = await createPool('oracle', this.cfg(this.source));
  }
  async openTarget(): Promise<void> {
    this.tClient = await createPool('oracle', this.cfg(this.target));
  }
  async close(): Promise<void> {
    if (this.sClient) await this.sClient.cleanup();
    if (this.tClient) await this.tClient.cleanup();
  }

  private async baseTables(client: SqlClient): Promise<BaseTable[]> {
    const rows = await client.query<Record<string, unknown>>(
      `SELECT table_name AS "name", NVL(num_rows, 0) AS "rows" FROM user_tables ORDER BY table_name`,
    );
    return rows.map((r) => ({ name: String(r['name']), rows: Number(r['rows'] ?? 0) }));
  }
  sourceBaseTables() {
    return this.baseTables(this.sClient);
  }
  targetBaseTables() {
    return this.baseTables(this.tClient);
  }

  async sourceForeignKeys() {
    const rows = await this.sClient.query<Record<string, unknown>>(
      `SELECT a.table_name AS "tbl", pk.table_name AS "ref"
       FROM user_constraints a
       JOIN user_constraints pk ON pk.constraint_name = a.r_constraint_name
       WHERE a.constraint_type = 'R'`,
    );
    return rows.map((r) => ({ table: String(r['tbl']), refTable: String(r['ref']) }));
  }

  private async count(client: SqlClient, table: string): Promise<number> {
    const r = await client.query<Record<string, unknown>>(
      `SELECT COUNT(*) AS "c" FROM ${id(table)}`,
    );
    return Number(r[0]?.['c'] ?? 0);
  }
  sourceCount(table: string) {
    return this.count(this.sClient, table);
  }
  targetCount(table: string) {
    return this.count(this.tClient, table);
  }

  private async primaryKey(table: string): Promise<string[]> {
    const rows = await this.sClient.query<Record<string, unknown>>(
      `SELECT cc.column_name AS "name"
       FROM user_constraints c
       JOIN user_cons_columns cc ON cc.constraint_name = c.constraint_name
       WHERE c.constraint_type = 'P' AND c.table_name = :1
       ORDER BY cc.position`,
      [table],
    );
    return rows.map((r) => String(r['name']));
  }

  private async columns(table: string): Promise<ColDdl[]> {
    const rows = await this.sClient.query<Record<string, unknown>>(
      `SELECT column_name AS "name", data_type AS "dataType",
              char_length AS "charLen", data_length AS "dataLen",
              data_precision AS "prec", data_scale AS "scale",
              CASE WHEN nullable = 'Y' THEN 'YES' ELSE 'NO' END AS "nullable",
              identity_column AS "identity", virtual_column AS "virtual",
              data_default AS "dflt"
       FROM user_tab_cols WHERE table_name = :1 AND hidden_column = 'NO' ORDER BY column_id`,
      [table],
    );
    return rows.map((r) => ({
      name: String(r['name']),
      dataType: String(r['dataType']),
      charLen: r['charLen'] == null ? null : Number(r['charLen']),
      dataLen: r['dataLen'] == null ? null : Number(r['dataLen']),
      prec: r['prec'] == null ? null : Number(r['prec']),
      scale: r['scale'] == null ? null : Number(r['scale']),
      nullable: String(r['nullable']).toUpperCase() === 'YES',
      identity: String(r['identity'] ?? '').toUpperCase() === 'YES',
      virtual: String(r['virtual'] ?? '').toUpperCase() === 'YES',
      default: r['dflt'] == null ? null : String(r['dflt']),
    }));
  }

  /** Writable columns (excludes virtual) + identity column names. */
  private async insertable(table: string) {
    const all = await this.columns(table);
    const writable = all.filter((c) => !c.virtual);
    return {
      cols: writable.map((c) => c.name),
      identityCols: writable.filter((c) => c.identity).map((c) => c.name),
    };
  }

  private buildCreateTable(table: string, cols: ColDdl[], pk: string[]): string {
    const defs = cols
      .filter((c) => !c.virtual)
      .map((c) => {
        let d = `  ${id(c.name)} ${typeString(c)}`;
        // Clone identity as BY DEFAULT so source values can be inserted.
        if (c.identity) d += ' GENERATED BY DEFAULT AS IDENTITY';
        else if (c.default !== null) d += ` DEFAULT ${c.default.trim()}`;
        if (!c.nullable && !c.identity) d += ' NOT NULL';
        return d;
      });
    if (pk.length) defs.push(`  PRIMARY KEY (${pk.map(id).join(', ')})`);
    return `CREATE TABLE ${id(table)} (\n${defs.join(',\n')}\n)`;
  }

  async createTableOnTarget(table: string): Promise<void> {
    const cols = await this.columns(table);
    const pk = await this.primaryKey(table);
    await this.tClient.query(this.buildCreateTable(table, cols, pk));
  }

  async truncateTarget(table: string): Promise<void> {
    await this.tClient.query(`DELETE FROM ${id(table)}`);
  }

  /** Build a row-value IN predicate over pk columns for the given tuples. */
  private keyIn(pk: string[], tuples: unknown[][]): { sql: string; binds: unknown[] } {
    const esc = pk.map(id);
    if (pk.length === 1) {
      const ph = tuples.map((_, i) => `:${i + 1}`).join(', ');
      return { sql: `${esc[0]} IN (${ph})`, binds: tuples.map((t) => t[0]) };
    }
    const rows = tuples
      .map(
        (_, ri) =>
          `(${esc.map((__, ci) => `:${ri * pk.length + ci + 1}`).join(', ')})`,
      )
      .join(', ');
    return { sql: `(${esc.join(', ')}) IN (${rows})`, binds: tuples.flat() };
  }

  async copyTable(
    table: string,
    conflict: Conflict,
    onProgress: (copied: number, total: number) => void,
  ): Promise<number> {
    const { cols, identityCols } = await this.insertable(table);
    if (cols.length === 0) return 0;
    const pk = await this.primaryKey(table);
    const pkIdx = pk.map((c) => cols.indexOf(c));
    const total = await this.sourceCount(table);
    const colList = cols.map(id).join(', ');
    const dedup = (conflict === 'skip' || conflict === 'upsert') && pk.length > 0;

    const copied = await this.tClient.transaction(async (tx: SqlExecutor) => {
      let n = 0;

      const flush = async (rowsData: unknown[][]) => {
        let rows = rowsData;
        if (dedup) {
          const tuples = rows.map((r) => pkIdx.map((i) => r[i]));
          const { sql, binds } = this.keyIn(pk, tuples);
          const existing = await tx.query<Record<string, unknown>>(
            `SELECT ${pk.map(id).join(', ')} FROM ${id(table)} WHERE ${sql}`,
            binds,
          );
          const seen = new Set(
            existing.map((e) => JSON.stringify(pk.map((c) => e[c] ?? null))),
          );
          if (conflict === 'upsert' && seen.size > 0) {
            // Replace existing rows: delete the matches, then insert all.
            const del = this.keyIn(pk, [...seen].map((s) => JSON.parse(s)));
            await tx.query(`DELETE FROM ${id(table)} WHERE ${del.sql}`, del.binds);
          } else if (conflict === 'skip') {
            rows = rows.filter(
              (r) => !seen.has(JSON.stringify(pkIdx.map((i) => r[i] ?? null))),
            );
          }
        }
        if (rows.length) await tx.bulkInsert(id(table), cols.map(id), rows);
      };

      if (pk.length === 1) {
        const key = pk[0];
        let last: unknown = null;
        for (;;) {
          const sql =
            last === null
              ? `SELECT ${colList} FROM ${id(table)} ORDER BY ${id(key)} FETCH FIRST :1 ROWS ONLY`
              : `SELECT ${colList} FROM ${id(table)} WHERE ${id(key)} > :1 ORDER BY ${id(key)} FETCH FIRST :2 ROWS ONLY`;
          const params = last === null ? [BATCH] : [last, BATCH];
          const rows = await this.sClient.query<Record<string, unknown>>(sql, params);
          if (rows.length === 0) break;
          await flush(rows.map((r) => cols.map((c) => r[c])));
          n += rows.length;
          last = rows[rows.length - 1][key];
          onProgress(n, total);
          if (rows.length < BATCH) break;
        }
      } else {
        let offset = 0;
        for (;;) {
          const rows = await this.sClient.query<Record<string, unknown>>(
            `SELECT ${colList} FROM ${id(table)} ORDER BY ROWID OFFSET :1 ROWS FETCH NEXT :2 ROWS ONLY`,
            [offset, BATCH],
          );
          if (rows.length === 0) break;
          await flush(rows.map((r) => cols.map((c) => r[c])));
          n += rows.length;
          offset += rows.length;
          onProgress(n, total);
          if (rows.length < BATCH) break;
        }
      }
      return n;
    });

    // Reseed identity columns so future inserts continue past the copied values.
    for (const col of identityCols) {
      try {
        await this.tClient.query(
          `ALTER TABLE ${id(table)} MODIFY (${id(col)} GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))`,
        );
      } catch {
        /* best-effort */
      }
    }
    return copied;
  }

  // ── script generation ──

  scriptHeader(sourceName: string, sourceDb: string): string[] {
    return [
      '-- Migration script generated by QuerySense (Oracle)',
      `-- Source: ${sourceName} (${sourceDb})`,
      '-- Note: foreign-key constraints and virtual columns are not recreated here.',
      '',
    ];
  }
  scriptFooter(): string[] {
    return ['COMMIT;'];
  }

  async scriptCreateTable(table: string): Promise<string[]> {
    const cols = await this.columns(table);
    const pk = await this.primaryKey(table);
    return [
      `BEGIN EXECUTE IMMEDIATE 'DROP TABLE ${id(table)} CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;`,
      '/',
      `${this.buildCreateTable(table, cols, pk)};`,
      '',
    ];
  }

  scriptTruncate(table: string): string {
    return `DELETE FROM ${id(table)};`;
  }

  /** Render a JS value as an Oracle SQL literal. */
  private literal(v: unknown): string {
    if (v === null || v === undefined) return 'NULL';
    if (typeof v === 'number' || typeof v === 'bigint') return String(v);
    if (typeof v === 'boolean') return v ? '1' : '0';
    if (v instanceof Date) return `TIMESTAMP '${v.toISOString().replace('T', ' ').replace('Z', '')}'`;
    if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'`;
    return `'${String(v).replace(/'/g, "''")}'`;
  }

  async scriptInserts(table: string, _conflict: Conflict, rowCap: number) {
    const { cols } = await this.insertable(table);
    const lines: string[] = [];
    if (cols.length === 0) return { lines, rows: 0, truncated: false };
    const colList = cols.map(id).join(', ');

    let offset = 0;
    let rows = 0;
    let truncated = false;
    for (;;) {
      if (rows >= rowCap) {
        truncated = true;
        lines.push(`-- NOTE: ${id(table)} truncated at ${rowCap} rows in this script. Use direct copy for the full table.`);
        break;
      }
      const data = await this.sClient.query<Record<string, unknown>>(
        `SELECT ${colList} FROM ${id(table)} ORDER BY ROWID OFFSET :1 ROWS FETCH NEXT :2 ROWS ONLY`,
        [offset, BATCH],
      );
      if (data.length === 0) break;
      for (const r of data) {
        const vals = cols.map((c) => this.literal(r[c])).join(', ');
        lines.push(`INSERT INTO ${id(table)} (${colList}) VALUES (${vals});`);
      }
      rows += data.length;
      offset += data.length;
      if (data.length < BATCH) break;
    }
    lines.push('');
    return { lines, rows, truncated };
  }
}
